### ISSUE TITLE
REST datasource config doesn't use baseURL.

### ISSUE THREAD

**Issue by Fennixx** [loopbackio/loopback-connector-rest#151]
## Steps to reproduce

When I fill baseURL in config for REST datasource (using loopback-connector-rest) it is not used anywhere.

## Current Behavior

```ts
baseURL: 'http://localhost:3000'
operations: [
{
      template: {
        method: 'GET',
        url: '/openapi.yaml',
      },
      functions: {
        getOpenApiSpecYAML: [],
      },
    },
]
```

when try to use this it will use only `/openapi.yaml`.

## Expected Behavior

I expect to have url composed from baseURL and url in operation: `http://localhost:3000/openapi.yaml`

## Additional information

**darwin x64 14.11.0**

```
├── @loopback/authentication-passport@3.0.2
├── @loopback/boot@3.0.2
├── @loopback/core@2.11.0
├── @loopback/repository@3.1.0
├── @loopback/rest@8.0.0
├── @loopback/rest-explorer@3.0.2
├── @loopback/service-proxy@3.0.2
├── loopback-connector-rest@3.7.0
```

**Comment by dhmlau** [comment]
@Fennixx, do you have a sample app that can be used for reproducing the problem? 
I've created an app some time ago https://github.com/dhmlau/loopback4-external-apis/blob/master/src/datasources/restds.datasource.json, and it seems to be working fine for me. Thanks.

**Comment by bajtos** [comment]
@dhmlau thank you for a link to a sample app using REST connector.

Notice that in your operation templates, you have to repeat `baseURL` prefix:

https://github.com/dhmlau/loopback4-external-apis/blob/0fa94809a686f75646ad7e9ba8c7c3f7a704348e/src/datasources/restds.datasource.json#L14-L17
```js
      "template": {
        "method": "GET",
        "url": "https://swapi.co/api/people/{personId}"
      },
```

As I understand @Fennixx's report, he is surprised that `baseURL` prefix is not applied automatically by the connector. Desired template:

```js
      "template": {
        "method": "GET",
        "url": "/people/{personId}"
      },
```

**Comment by Fennixx** [comment]
Hello @dhmlau,
I have app, but not simple and cant be shared easily, but this issue is the same everywhere. How you check if it is working?
I see in your JSON file that you have 
`"baseURL": "https://swapi.co/api/"`
and then
`"url": "https://swapi.co/api/people/{personId}"`
so in your example it is not working as expected, because if it will you should have final URL like this:
`https://swapi.co/api/https://swapi.co/api/people/{personId}`.

I think baseURL should be prefix of all URLs in operations.
Exactly as @bajtos say.

**Comment by bajtos** [comment]
> so in your example it is not working as expected, because if it will you should have final URL like this:
> `https://swapi.co/api/https://swapi.co/api/people/{personId}`.

I don't think we should be blindly concatenating `baseURL` with template url for two reasons:

1. We should to preserve backwards compatibility for existing users with template defined using absolute URLs.
2. I can imagine cases where we want `baseURL` like `https://swapi.co/api/` to be applied to most operations, but also have few operations on a different base path, e.g. `https://swapi.co/status` where the template provides the full URL.

I would like the template logic work as follows:

- If the URL is an absolute one (starting with `http://` or `https://`), then we leave it as-is.
- Otherwise we join `baseURL` with template `url`.
- It's important to handle the edge case where `baseURL` ends with `/` and `url` starts with `/` too, we don't want to create URLs with doubled path separator (`https://swapi.co/api//people`).

Here is the code that's compiling an operation template:

https://github.com/strongloop/loopback-connector-rest/blob/5e6d3c7bd5f66ee9d012e299f3895fcf09dadfbe/lib/rest-connector.js#L56-L57

And here we are invoking the operation to handle an incoming request:

https://github.com/strongloop/loopback-connector-rest/blob/5e6d3c7bd5f66ee9d012e299f3895fcf09dadfbe/lib/rest-connector.js#L119-L122

I see two possible ways how to apply `baseURL` (there maybe more):

1. Modify `op.template.url` & apply `baseURL` just before we call `RequestBuilder.compile`: https://github.com/strongloop/loopback-connector-rest/blob/5e6d3c7bd5f66ee9d012e299f3895fcf09dadfbe/lib/rest-connector.js#L56-L57
2. Modify request builder to apply `baseURL` just before a JSON template is created: https://github.com/strongloop/loopback-connector-rest/blob/5e6d3c7bd5f66ee9d012e299f3895fcf09dadfbe/lib/rest-builder.js#L60-L75

I think I slightly prefer the first option, because it's slightly more performant - it applies `baseURL` only once at app startup. The second option will deal with `baseURL` on every request.

**Comment by bajtos** [comment]
@Fennixx can you try if the following configuration works as a workaround?

```
options: {
  baseUrl: 'http://localhost:3000'
},
operations: [
{
      template: {
        method: 'GET',
        url: '/openapi.yaml',
      },
      functions: {
        getOpenApiSpecYAML: [],
      },
    },
]
```

Explanation:

https://github.com/strongloop/loopback-connector-rest/blob/5e6d3c7bd5f66ee9d012e299f3895fcf09dadfbe/lib/rest-connector.js#L153-L155

https://github.com/strongloop/loopback-connector-rest/blob/5e6d3c7bd5f66ee9d012e299f3895fcf09dadfbe/lib/rest-connector.js#L165-L167

**Comment by Fennixx** [comment]
@bajtos I tried the suggested workaround:
```ts
options: {
  baseUrl: 'http://localhost:3000'
},
operations: [
{
      template: {
        method: 'GET',
        url: '/openapi.yaml',
      },
      functions: {
        getOpenApiSpecYAML: [],
      },
    },
]
``` 

And it is not woking. I have error:
`Error: Invalid URI "/openapi.yaml"`
